[tools]
"aqua:koalaman/shellcheck" = "0.11.0"
"aqua:mvdan/sh" = "latest"

[env]
X_PODMAN_COMMON = "--format=oci --layers=false --squash-all --identity-label=false --omit-history"
X_PODMAN_MANIFEST_REGISTRY = "localhost"
